services:
  frontend:
    build: . 
    container_name: frontend 
    env_file: ".env"
    ports:
      - "5173:5173"  
    volumes:
      - ./react:/app   
      - /app/node_modules
    restart: unless-stopped


    